# permissions for end users to edit jackoperatortests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: jackoperatortest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jack-operator-test
    app.kubernetes.io/part-of: jack-operator-test
    app.kubernetes.io/managed-by: kustomize
  name: jackoperatortest-editor-role
rules:
- apiGroups:
  - jack.jack.operator.test
  resources:
  - jackoperatortests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jack.jack.operator.test
  resources:
  - jackoperatortests/status
  verbs:
  - get
